### ISSUE TITLE
GEN-11: Revise the Notifications

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#163]
### What's up?

Within the scope of #162, we are expected to revise the _Notification_ subtitle under the System Requirements and develop possible improvements.

### To Do

- [x] Revise the _Notification_ related System Requirements.
- [x] Share your ideas with other team members in the next meeting on 16.10.22 @18.00.

### Deadline

16.10.22 @18.00

### Reviewers

@MustafaEmreErengul

**Comment by KarahanS** [comment]
Requirements under _Notification_ organized according to the contexts. We have to update the indices in our scenarios and mockups. Waiting for now in case of any other change/addition.

**Comment by BElifb** [comment]
* I think that the last group of  requirements should exist as independent items. Since errors can happen regarding topics other than copyright. Updated accordingly. (1.2.1.4)
* I also think that the admin/moderator should directly intervene in the copyright issues, as opposed to notifying the faulty user since they very likely will not be inclined to make the requested change. (1.2.1.4.3) Updated accordingly.
* 1.1.5 Copyright infringement should be updated accordingly.

**Comment by KarahanS** [comment]
Removed the following part from the requirements and updated the indices (since we decided not to require someone to accept a "follow request" when he is followed by another user):
> * 1.2.1.3. System shall send notifications to the users related to the following functionality.
            1.2.1.3.1. Users shall be notified when they receive a follow request.
            1.2.1.3.2. Users shall be notified when their follow request is accepted. 
            1.2.1.3.3. Users shall not be notified when their follow request is rejected.

**Comment by MustafaEmreErengul** [comment]
Since the deadline has passed, the current version of the Notifications page is reviewed. No further action is required, closing the issue.
