### ISSUE TITLE
Requirements: Specification of User Requirements 

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#21]
**To Do**: Specify the user requirements. It's the first phase of the requirements engineering process and requirements may be updated or modified as we progress. Determine the necessary questions for the user requirements. After determining them individually, hold a discussion about the requirements and make necessary adjusment as a group.

Deadline: <del>22.03.2022 @18.00</del>
14.04.2022 @23.59 (extended)

**Comment by KarahanS** [comment]
Draft of user requirements are added [here](https://github.com/bounswe/bounswe2022group8/wiki/Requirements). Please review and expand the requirements/glossary for the missing parts: @serdarakol @dundarmete

**Comment by KarahanS** [comment]
Requirements must be clarified and we should provide more details about the nature of each requirement. Review the user requirements [here](https://github.com/bounswe/bounswe2022group8/wiki/Requirements) and make necessary updates to comply with the structure given in the *[Requirements Validation and Writing the Requirements](https://moodle.boun.edu.tr/mod/resource/view.php?id=579802)*.

**Comment by serdarakol** [comment]
@KarahanS I am still reviewing, kindly requesting 2 days extension 18.03.2022 @22:00

**Comment by KarahanS** [comment]
Modified the **1.1.3. Profile Management** subsection and transferred some articles to **1.1.4. User Interaction** subsection. Created **1.1.5 Exhibitions** subsection. Added 1.1.4.1, 1.1.4.2, 1.1.4.3, 1.1.4.4, 1.1.4.5, 1.1.4.6, 1.1.5.1, 1.1.5.2, 1.1.5.3, 1.1.5.4, 1.1.5.5 and 1.1.5.6. Updated corresponding article references in scenarios and mockups.

**Comment by sinemKocoglu** [comment]
Requirements 1.2.4 Payment System is renamed as Bidding System because platform doesn't provide any functionality for payment system as decided in customer meeting.
1.2.4.1. Level of artist who can sell art item is stated.
1.2.4.2 is replaced. No payment system.
* 1.2.4.2  In offers page, offers of artists who are in level of 1,called registered users, are ordered in descending order.
is added.
1.2.5.1. is clarified by the definition of popularity.
1.2.8.3.1. Abilities of users are added level by level to the Level System.

**Comment by KarahanS** [comment]
First phase of the requirements elicitation is completed. Will update the requirements until Milestone.
