### ISSUE TITLE
MIL-31: Changes in development process

### ISSUE THREAD

**Issue by mumcusena** [bounswe/bounswe2022group8#427]
### What's up?

In the final Milestone Group review the executive summary should mention about the changes we made in the development process. 

### To Do

- [x] Describe any changes your team has made or planned based on previous milestones to improve the development process, explain how those changes will impact your process.

### Deadline

02.01.2023 @23.55 **strict**

**Comment by mumcusena** [comment]
I added a section called 'Changes in Development Process' to the final milestone group review doc. You can see it [here](https://github.com/bounswe/bounswe2022group8/blob/master/Deliverables/CMPE451_Customer_Presentation_Milestone_3/Group%20Review.md).

**Comment by mumcusena** [comment]
please review: @BElifb @KarahanS @serdarakol

**Comment by KarahanS** [comment]
Reviewed, thanks for the efforts. Some problems I've noticed:
> After Milestone 2, we had **a little missing functionalities** in the backend. 
* Well unfortunately, this is not totally correct :D
> This way we could show all of the implemented functionalities of the backend in the demo presentation.
* Did you use **could** as **we could have** here. Is it the case? Because unfortunately we couldn't show all of the implemented functionalities in the demo. 
> Text and image annotations
Lexical search
Recommendation system that tracks the user activity
Bidding system for the art items

*Offline and virtual exhibitions* are missing here - which took a majority of our time (it has this [PR](https://github.com/bounswe/bounswe2022group8/pull/344) which is the most commented PR we have so far :D - thanks to detailed review of @BElifb)
* Semantic search is missing. 
* Copyright is missing.
* Ticket system is missing.
* We discussed and assigned all the tasks above, if you're not planning to add them to the list, I think you should change this line then:
> The prioritizing of the implementation of the remaining functionalities helped us showcase the following functionalities.

We can change it like "Features implemented in the remaining time were: ...".

**Comment by mumcusena** [comment]
* I deleted the word 'little'
* added offline and virtual exhibitions (so sorry for missing that out)]
* change the to to "Features implemented in the remaining time were:"

@KarahanS

**Comment by mumcusena** [comment]
Closing, since it is completed and approved.
