### ISSUE TITLE
Requirements Elicitations: Review Requirements

### ISSUE THREAD

**Issue by mumcusena** [bounswe/bounswe2022group8#56]
*To Do:* Review existing requirements in terms of their completeness, unambiguity. verifiability and necessity.

- [x] @mumcusena 
- [x] @KarahanS 
- [x] @serdarakol 
- [x] @mustafa-cihan 
- [x] @BElifb 
- [x] @kostanya 
- [x] @sinemKocoglu 
- [x] @ooodogodogodogo 
- [x] @dundarmete 
- [x] @simsekhebun 

_Deadline: 15.04.2022 @17.00_

**Comment by KarahanS** [comment]
Contributed to the [Requirements](https://github.com/bounswe/bounswe2022group8/wiki/Requirements) section under the sub-issues #53, #54, #62 (revision + contribution), #69, #76. Expanded the glossary along the way and reviewed the entire requirements page couple of times to identify problems if any.

**Comment by serdarakol** [comment]
I have reviewed most of the requirements and made necessary changes and comments. on #71 #56 #76. #69

**Comment by BElifb** [comment]
* Rewrote the bidding system requirements [#64 ](https://github.com/bounswe/bounswe2022group8/issues/64#issue-1194941813).
*  Reviewed the entire requirements, made the following changes:
    *  Modified Capacity requirements [#75 ](https://github.com/bounswe/bounswe2022group8/issues/75)
    *  Modified rest of the non-functional requirements in accordance with the fact that system no longer offers a payments system.
    * Modified the Exhibition requirements [#68 ](https://github.com/bounswe/bounswe2022group8/issues/68)
    * Made additions/changes to the glossary as the need arose. [#35 ](https://github.com/bounswe/bounswe2022group8/issues/35).
    * Made other minor changes in various places. Refer to todays revisions for more detailed information.  

**Question:**    
* Moderator is referred to as **the moderator** in some parts. Wouldn't it be better to refer as **a** moderator? Any volunteers to change it ?

**Comment by KarahanS** [comment]
It's better to have **a moderator00 rather than **the moderator** in order to enable presence of more than one moderators in the system. If we find it unnecessary, then we can keep just one moderator (and technically it doesn't contradict with the **a** moderator statement)
Made the following changes:
* Change the definition of the *active user* so that it contains *a* moderator rather than *the*. 
* Updated definition of ticket to include *moderator* rather than *admin*.
* Updated definition of moderator to include:
> Moderator and admin can be used interchangeably for the project although we sticked to the term, moderator
* Switched from **the** to **a** in the following requirements:
> 1.1.5.2. Active users shall be able to submit a copyright ticket to a moderator regarding a copyright issue.
1.1.5.3. A moderator shall be able to receive a copyright ticket from another user.
1.1.5.4. A moderator shall be able to ban a user that was mentioned in the copyright ticket and that didn't remove the art item related to the copyright ticket.
1.1.5.5. A moderator shall be able to send an item removal request notation to the user that was mentioned in the copyright ticket.
1.1.5.6. Registered users shall be able to write reports to a moderator about inappropriate content
 
 > 1.2.4.13. In case of a conflict, the system shall provide both parties of the sale (seller and the bidder), with the ability to submit a ticket to a moderator specifying the problem.

**Comment by sinemKocoglu** [comment]
Review and additions are made in Annotation, Exhibition and Notification requirements. Related issues #76, #68, #66.

**Comment by ooodogodogodogo** [comment]
Reviewed and nothing added or changed.

**Comment by dundarmete** [comment]
Reviewed and nothing added or changed.

**Comment by simsekhebun** [comment]
Reviewed and nothing changed.

**Comment by KarahanS** [comment]
**Requirements  v1.0** is done.
