### ISSUE TITLE
Requirements Elicitation: Bidding System

### ISSUE THREAD

**Issue by BElifb** [bounswe/bounswe2022group8#64]
During the processes of Mockups, Customer Meeting and the creation of UML diagrams bidding system went through some major changes. As the last phase of the requirement elicitation, 1.2.4. Bidding System of [Requirements page](https://github.com/bounswe/bounswe2022group8/wiki/Requirements) must be revised and updated in accordance with our software design.

**To Do:**
*  Update the 1.2.4. Bidding System of [Requirements page](https://github.com/bounswe/bounswe2022group8/wiki/Requirements) in order to include different functionalities discussed in the meetings and specified in the UML diagrams.
* Update the [glossary](https://github.com/bounswe/bounswe2022group8/wiki/Requirements#glossary) if necessary.

**Deadline:** 10.04.2022 @20.00

**Comment by BElifb** [comment]
Updated requirement **1.2.4.1** and added requirements **1.2.4.2 through 1.2.4.18.**
Updated **Bid** in the glossary and added **Seller**, **Bidder** and **For sale**.

**Comment by KarahanS** [comment]
Reviewed the Bidding system requirements. It covers what we have discussed about the bidding system, and there doesn't seem to be any contradiction. Thanks for the effort. Reference in **1.2.4.8.** will have to be updated since article numbers will change as we contribute to the requirements page inevitably.
