### ISSUE TITLE
Creating diagram phases of the project

### ISSUE THREAD

**Issue by serdarakol** [bounswe/bounswe2022group8#78]
Creating a arc arrowed circular project phase diagram for the milestone

**Comment by serdarakol** [comment]
I have created a lucidchart. It is on the second page of the usecase diagram page. Lucid.chart link is also shared on the discord channel 
Review needed before adding the diagram to the milestone report.
@simsekhebun could you please review it

**Comment by mumcusena** [comment]
I reviewed the chart, it summarizes the work done until the first milestone correctly. I made a little change in the description of weeks 1-2. The changed description is as follows: 
 * We created and customized our wiki page, and created the first issues and our communication plan in order to set the infrastructure.

**Comment by serdarakol** [comment]
Thank you, sena I am closing the issue
