### ISSUE TITLE
Playing with Git commands

### ISSUE THREAD

**Issue by serdarakol** [bounswe/bounswe2022group8#86]
### What's up?

playing with git commands and getting used to it. It is a self study issue.

### To Do

creating .gitignore file to the practice app directory

### Deadline

26.04.2022 @ 10:00

### Reviewers

@BElifb I created a mock file that might not be needed. Could you also briefly explain how to send a pull request to specific person. I was always sending direct push command it does not create any pull request and it automatically merges.

**Comment by BElifb** [comment]
@serdarakol I think I just added people as reviewers, don't know if there is any other way to specifically assign. Also I think you need to commit (or push to) a branch other than main in order to create merge pull request later (So that someone else can review before it's merged). Once you've done that I think a button appears on the homepage to create a pull request (you can then specify reviewers etc.), but you should also be able create one manually from Pull requests tab.
